# Digital Echo Plex Deployment Configuration

# Build configuration for Astro
build:
  outDir: dist
  target: es2020
  minify: true
  sourcemap: false

# Server configuration
server:
  host: 0.0.0.0
  port: 3000
  cors: true

# Static file handling
static:
  directory: public
  mountPath: /

# Environment variables
env:
  production: true
  NODE_ENV: production

# Deployment settings
deploy:
  site: digital-echoplex
  provider: netlify
  buildCommand: npm run build
  outputDirectory: dist
  publishDirectory: dist
  autoPublish: true
  
# PWA configuration
pwa:
  enabled: true
  manifest:
    name: Digital Echo Plex
    short_name: EchoPlex
    description: Web-based implementation of the Echo Plex looper
    start_url: /
    display: standalone
    background_color: "#1a1a1a"
    theme_color: "#00ff00"
    icons:
      - src: "/icons/icon-72x72.png"
        sizes: "72x72"
        type: "image/png"
      - src: "/icons/icon-96x96.png"
        sizes: "96x96"
        type: "image/png"
      - src: "/icons/icon-128x128.png"
        sizes: "128x128"
        type: "image/png"
      - src: "/icons/icon-144x144.png"
        sizes: "144x144"
        type: "image/png"
      - src: "/icons/icon-152x152.png"
        sizes: "152x152"
        type: "image/png"
      - src: "/icons/icon-192x192.png"
        sizes: "192x192"
        type: "image/png"
      - src: "/icons/icon-384x384.png"
        sizes: "384x384"
        type: "image/png"
      - src: "/icons/icon-512x512.png"
        sizes: "512x512"
        type: "image/png"
